'use client';
import './globals.css';
import { Inter } from 'next/font/google';
import Layout from './theme/Layout/Layout';
import { ColorModeScript, useColorMode } from '@chakra-ui/react';
import { Topbar } from './components/Topbar';

const inter = Inter({ subsets: ['latin'] });

const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ColorModeScript initialColorMode={'dark'} />
                <Layout>
                    <Topbar />
                    {children}
                </Layout>
            </body>
        </html>
    );
}
